<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestauranteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $restaurantes = [
            [
                'nome' => 'Jamile',
                'tipos' => json_encode(['brasileira', 'contemporanea', 'gourmet']),
                'avaliacao' => 4.9,
                'endereco' => 'R. Treze de Maio, 647 - Bela Vista, São Paulo',
                'horario' => 'Segunda a Domingo: 12:00 - 23:00',
                'preco' => 'luxo',
                'precoTexto' => '$$$$',
                'cidade' => 'sao-paulo',
                'imagem' => 'https://i.ibb.co/wNDYyrGF/image.png',
                'badge' => 'Premium',
                'promocao' => false,
                'link' => 'restaurante/jamile',
                'lat' => -23.5505,
                'lng' => -46.6333,
            ],
            [
                'nome' => 'Casa Terracota',
                'tipos' => json_encode(['gourmet', 'inovador', 'elegante']),
                'avaliacao' => 4.7,
                'endereco' => 'Av. das Flores, 456 - Gramado, RS',
                'horario' => 'Terça a Sábado: 19:00 - 23:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'rio-grande-do-sul',
                'imagem' => 'https://i.ibb.co/sJyf79Pw/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/casa-terracota',
                'lat' => -29.3739,
                'lng' => -50.8811,
            ],
            [
                'nome' => 'El Fuego',
                'tipos' => json_encode(['fondue', 'carne', 'queijo']),
                'avaliacao' => 4.6,
                'endereco' => 'Rua dos Pinheiros, 789 - Gramado, RS',
                'horario' => 'Quarta a Domingo: 18:00 - 22:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'rio-grande-do-sul',
                'imagem' => 'https://i.ibb.co/p6CszR4h/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/el-fuego',
                'lat' => -29.3749,
                'lng' => -50.8821,
            ],
            [
                'nome' => 'Oro',
                'tipos' => json_encode(['brasileira', 'gourmet', 'contemporanea']),
                'avaliacao' => 4.9,
                'endereco' => 'Av. Gen. San Martin, 889 - Leblon, Rio de Janeiro',
                'horario' => 'Terça a Sábado: 19:00 - 23:00',
                'preco' => 'luxo',
                'precoTexto' => '$$$$',
                'cidade' => 'rio-de-janeiro',
                'imagem' => 'https://i.ibb.co/wNDYyrGF/image.png',
                'badge' => 'Premium',
                'promocao' => false,
                'link' => 'restaurante/oro',
                'lat' => -22.9792,
                'lng' => -43.2236,
            ],
            [
                'nome' => 'Cipriani',
                'tipos' => json_encode(['italiana', 'contemporanea', 'gourmet']),
                'avaliacao' => 4.9,
                'endereco' => 'Av. Atlântica, 1702 - Copacabana, Rio de Janeiro',
                'horario' => 'Segunda a Domingo: 19:00 - 21:00',
                'preco' => 'luxo',
                'precoTexto' => '$$$$',
                'cidade' => 'rio-de-janeiro',
                'imagem' => 'https://i.ibb.co/NnswBt5Q/image.png',
                'badge' => 'Premium',
                'promocao' => false,
                'link' => 'restaurante/cipriani',
                'lat' => -22.9711,
                'lng' => -43.1828,
            ],
            [
                'nome' => 'Fasano',
                'tipos' => json_encode(['italiana', 'gourmet', 'contemporanea']),
                'avaliacao' => 4.9,
                'endereco' => 'Av. Vieira Souto, 80 - Ipanema, Rio de Janeiro',
                'horario' => 'Segunda a Domingo: 12:00 - 23:00',
                'preco' => 'luxo',
                'precoTexto' => '$$$$',
                'cidade' => 'rio-de-janeiro',
                'imagem' => 'https://i.ibb.co/Rk9CXfxM/image.png',
                'badge' => 'Premium',
                'promocao' => false,
                'link' => 'restaurante/fasano',
                'lat' => -22.9785,
                'lng' => -43.2089,
            ],
            [
                'nome' => 'Terraço Itália',
                'tipos' => json_encode(['italiana', 'gourmet']),
                'avaliacao' => 4.8,
                'endereco' => 'Rua Floriano Peixoto, 158, São Paulo, SP',
                'horario' => 'Segunda a Sexta: 11:00 - 19:30',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'sao-paulo',
                'imagem' => 'https://i.ibb.co/n8syZSDs/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/terraco-italia',
                'lat' => -23.5505,
                'lng' => -46.6333,
            ],
            [
                'nome' => 'Porto Canoas',
                'tipos' => json_encode(['frutos-do-mar', 'peixes']),
                'avaliacao' => 4.5,
                'endereco' => 'Av. das Cataratas, 202 - Foz do Iguaçu, PR',
                'horario' => 'Todos os dias: 11:00 - 23:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'parana',
                'imagem' => 'https://i.ibb.co/YBXdWS3Q/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/porto-canoas',
                'lat' => -25.5478,
                'lng' => -54.5873,
            ],
            [
                'nome' => 'Rafain',
                'tipos' => json_encode(['churrasco', 'cultural']),
                'avaliacao' => 4.3,
                'endereco' => 'Rua das Danças, 303 - Foz do Iguaçu, PR',
                'horario' => 'Quinta a Domingo: 19:00 - 00:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'parana',
                'imagem' => 'https://i.ibb.co/B50ZTNgP/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/rafain',
                'lat' => -25.5488,
                'lng' => -54.5883,
            ],
            [
                'nome' => 'La Mafia Trattoria',
                'tipos' => json_encode(['italiana', 'tradicional']),
                'avaliacao' => 4.4,
                'endereco' => 'Rua das Tradições, 101 - Foz do Iguaçu, PR',
                'horario' => 'Segunda a Sábado: 18:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'parana',
                'imagem' => 'https://i.ibb.co/5W1XfZVG/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/la-mafia-trattoria',
                'lat' => -25.5498,
                'lng' => -54.5893,
            ],
            [
                'nome' => 'Bené da Flauta',
                'tipos' => json_encode(['tradicional', 'brasileira']),
                'avaliacao' => 4.5,
                'endereco' => 'Rua das Tradições, 101 - Ouro Preto, MG',
                'horario' => 'Segunda a Sábado: 18:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'minas-gerais',
                'imagem' => 'https://i.ibb.co/5W1XfZVG/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/bene-da-flauta',
                'lat' => -20.3822,
                'lng' => -43.5039,
            ],
            [
                'nome' => 'Gastro Pub',
                'tipos' => json_encode(['moderna', 'pub']),
                'avaliacao' => 4.4,
                'endereco' => 'Rua dos Ingleses, 118 - Ouro Preto, MG',
                'horario' => 'Segunda a Sábado: 12:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'minas-gerais',
                'imagem' => 'https://i.ibb.co/DP0nRQ81/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/gastro-pub',
                'lat' => -20.3832,
                'lng' => -43.5049,
            ],
            [
                'nome' => 'Contos dos Reis',
                'tipos' => json_encode(['tradicional', 'brasileira']),
                'avaliacao' => 4.3,
                'endereco' => 'Rua das Danças, 303 - Ouro Preto, MG',
                'horario' => 'Quinta a Domingo: 19:00 - 00:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'minas-gerais',
                'imagem' => 'https://i.ibb.co/kVDCLyJK/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/contos-dos-reis',
                'lat' => -20.3842,
                'lng' => -43.5059,
            ],
            [
                'nome' => 'Mangue',
                'tipos' => json_encode(['regional', 'frutos-do-mar']),
                'avaliacao' => 4.5,
                'endereco' => 'Rua das Tradições, 101 - Barreirinhas, MA',
                'horario' => 'Segunda a Sábado: 18:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'maranhao',
                'imagem' => 'https://i.ibb.co/wNDYyrGF/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/mangue',
                'lat' => -2.7478,
                'lng' => -42.8297,
            ],
            [
                'nome' => 'A Canoa',
                'tipos' => json_encode(['regional', 'frutos-do-mar']),
                'avaliacao' => 4.4,
                'endereco' => 'Rua dos Ingleses, 118 - Barreirinhas, MA',
                'horario' => 'Segunda a Sábado: 12:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'maranhao',
                'imagem' => 'https://i.ibb.co/NnswBt5Q/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/a-canoa',
                'lat' => -2.7488,
                'lng' => -42.8307,
            ],
            [
                'nome' => 'Terral',
                'tipos' => json_encode(['regional', 'frutos-do-mar']),
                'avaliacao' => 4.3,
                'endereco' => 'Rua das Danças, 303 - Barreirinhas, MA',
                'horario' => 'Quinta a Domingo: 19:00 - 00:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'maranhao',
                'imagem' => 'https://i.ibb.co/Rk9CXfxM/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/terral',
                'lat' => -2.7498,
                'lng' => -42.8317,
            ],
            [
                'nome' => 'Alameda - Jurerê',
                'tipos' => json_encode(['contemporânea', 'gourmet']),
                'avaliacao' => 4.7,
                'endereco' => 'Rua das Praias, 101 - Florianópolis, SC',
                'horario' => 'Segunda a Domingo: 18:00 - 23:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'santa-catarina',
                'imagem' => 'https://i.ibb.co/cGRyypv/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/alameda-jurere',
                'lat' => -27.4500,
                'lng' => -48.5490,
            ],
            [
                'nome' => 'Olivia Cucina',
                'tipos' => json_encode(['italiana', 'tradicional']),
                'avaliacao' => 4.6,
                'endereco' => 'Rua dos Ingleses, 118 - Florianópolis, SC',
                'horario' => 'Segunda a Sábado: 12:00 - 23:00',
                'preco' => 'medio',
                'precoTexto' => '$$',
                'cidade' => 'santa-catarina',
                'imagem' => 'https://i.ibb.co/Y4KQnVm6/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/olivia-cucina',
                'lat' => -27.4510,
                'lng' => -48.5500,
            ],
            [
                'nome' => 'Dolce Vita',
                'tipos' => json_encode(['italiana', 'gourmet']),
                'avaliacao' => 4.5,
                'endereco' => 'Rua das Danças, 303 - Florianópolis, SC',
                'horario' => 'Quinta a Domingo: 19:00 - 00:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'santa-catarina',
                'imagem' => 'https://i.ibb.co/nqHsNL4R/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/dolce-vita',
                'lat' => -27.4520,
                'lng' => -48.5510,
            ],
            [
                'nome' => 'Capim Santo',
                'tipos' => json_encode(['brasileira', 'contemporânea']),
                'avaliacao' => 4.5,
                'endereco' => 'Av. Brig. Faria Lima, 2705 - Jardim Paulistano, São Paulo - SP, 01451-000',
                'horario' => 'Terça a Segunda: 10:00 - 18:00',
                'preco' => 'alto',
                'precoTexto' => '$$$',
                'cidade' => 'sao-paulo',
                'imagem' => 'https://i.ibb.co/B2sZMYRW/image.png',
                'badge' => null,
                'promocao' => false,
                'link' => 'restaurante/capim-santo',
                'lat' => -23.5688,
                'lng' => -46.6824,
            ],
        ];

        DB::table('restaurantes')->insert($restaurantes);
    }
}
